apiVersion: apps/v1
kind: Deployment
metadata:
  name: shadow-sidecar
  namespace: shadow-system
  labels:
    app: shadow-sidecar
    component: sidecar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shadow-sidecar
  template:
    metadata:
      labels:
        app: shadow-sidecar
        component: sidecar
    spec:
      serviceAccountName: shadow-sidecar
      containers:
      - name: sidecar
        image: shadow/sidecar:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "8080"
        - name: WORKSPACE_DIR
          value: "/workspace"
        - name: LOG_LEVEL
          value: "info"
        - name: MAX_FILE_SIZE_MB
          value: "50"
        - name: COMMAND_TIMEOUT_MS
          value: "30000"
        - name: RATE_LIMIT_WINDOW_MS
          value: "60000"
        - name: RATE_LIMIT_MAX_REQUESTS
          value: "100"
        - name: CORS_ORIGIN
          value: "*"
        - name: ENABLE_COMMAND_APPROVAL
          value: "false"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: workspace
          mountPath: /workspace
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1001
          capabilities:
            drop:
            - ALL
      volumes:
      - name: workspace
        emptyDir: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shadow-sidecar
  namespace: shadow-system