apiVersion: v1
kind: Service
metadata:
  name: shadow-sidecar
  namespace: shadow-system
  labels:
    app: shadow-sidecar
    component: sidecar
spec:
  type: ClusterIP
  selector:
    app: shadow-sidecar
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
---
# NetworkPolicy to restrict access to sidecar
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: shadow-sidecar-network-policy
  namespace: shadow-system
spec:
  podSelector:
    matchLabels:
      app: shadow-sidecar
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    # Allow traffic from pods in the same namespace
    - namespaceSelector:
        matchLabels:
          name: shadow-system
    # Allow traffic from task pods
    - podSelector:
        matchLabels:
          component: task-agent
    ports:
    - protocol: TCP
      port: 8080
  egress:
  # Allow DNS
  - to:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: UDP
      port: 53
  # Allow outbound HTTPS for package downloads
  - to:
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 443
  # Allow outbound HTTP
  - to:
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 80