# ServiceMonitor for Prometheus monitoring (if using Prometheus Operator)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: shadow-agents-monitor
  namespace: shadow-agents
  labels:
    app: shadow
    component: monitoring
spec:
  selector:
    matchLabels:
      app: shadow-agent
  endpoints:
  - port: api
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
---
# Pod monitor for direct pod monitoring
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: shadow-agent-pods
  namespace: shadow-agents
  labels:
    app: shadow
    component: monitoring
spec:
  selector:
    matchLabels:
      app: shadow-agent
  podMetricsEndpoints:
  - port: api
    path: /metrics
    interval: 30s
---
# Grafana dashboard ConfigMap (optional)
apiVersion: v1
kind: ConfigMap
metadata:
  name: shadow-agents-dashboard
  namespace: shadow-agents
  labels:
    app: shadow
    component: monitoring
    grafana_dashboard: "1"
data:
  shadow-agents.json: |
    {
      "dashboard": {
        "id": null,
        "title": "Shadow Agents",
        "tags": ["shadow", "agents"],
        "style": "dark",
        "timezone": "browser",
        "panels": [
          {
            "id": 1,
            "title": "Active Agent Pods",
            "type": "stat",
            "targets": [
              {
                "expr": "count(up{job=\"shadow-agents-monitor\"} == 1)",
                "legendFormat": "Active Pods"
              }
            ],
            "gridPos": {"h": 8, "w": 12, "x": 0, "y": 0}
          },
          {
            "id": 2,
            "title": "Pod Health Status",
            "type": "table",
            "targets": [
              {
                "expr": "up{job=\"shadow-agents-monitor\"}",
                "legendFormat": "{{pod}}"
              }
            ],
            "gridPos": {"h": 8, "w": 12, "x": 12, "y": 0}
          },
          {
            "id": 3,
            "title": "CPU Usage",
            "type": "timeseries",
            "targets": [
              {
                "expr": "rate(container_cpu_usage_seconds_total{namespace=\"shadow-agents\"}[5m])",
                "legendFormat": "{{pod}}"
              }
            ],
            "gridPos": {"h": 8, "w": 24, "x": 0, "y": 8}
          },
          {
            "id": 4,
            "title": "Memory Usage",
            "type": "timeseries",
            "targets": [
              {
                "expr": "container_memory_usage_bytes{namespace=\"shadow-agents\"}",
                "legendFormat": "{{pod}}"
              }
            ],
            "gridPos": {"h": 8, "w": 24, "x": 0, "y": 16}
          }
        ],
        "time": {
          "from": "now-1h",
          "to": "now"
        },
        "refresh": "30s"
      }
    }