# Storage class for agent workspaces (adjust for your cluster)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: shadow-workspace-storage
  labels:
    app: shadow
    component: storage
# Adjust provisioner and parameters for your cluster
provisioner: kubernetes.io/gce-pd  # Change to your storage provisioner
parameters:
  type: pd-ssd
  replication-type: none
  zones: us-central1-a,us-central1-b
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
# Resource quota for agent namespace
apiVersion: v1
kind: ResourceQuota
metadata:
  name: shadow-agents-quota
  namespace: shadow-agents
  labels:
    app: shadow
    component: quota
spec:
  hard:
    # Pod limits
    pods: "50"
    requests.cpu: "20"
    requests.memory: 40Gi
    limits.cpu: "50"
    limits.memory: 100Gi
    
    # Storage limits
    persistentvolumeclaims: "0"  # Using emptyDir only
    requests.storage: "0"
    
    # Service limits
    services: "50"
    
    # Other resources
    configmaps: "10"
    secrets: "10"
---
# Limit range for individual pods
apiVersion: v1
kind: LimitRange
metadata:
  name: shadow-agents-limits
  namespace: shadow-agents
  labels:
    app: shadow
    component: limits
spec:
  limits:
  - type: Pod
    max:
      cpu: "4"
      memory: 8Gi
    min:
      cpu: "100m"
      memory: 128Mi
  - type: Container
    default:
      cpu: "500m"
      memory: 1Gi
    defaultRequest:
      cpu: "250m"
      memory: 512Mi
    max:
      cpu: "2"
      memory: 4Gi
    min:
      cpu: "100m"
      memory: 128Mi
  - type: PersistentVolumeClaim
    max:
      storage: 20Gi
    min:
      storage: 1Gi